# Generated by Django 3.1.7 on 2021-06-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('created_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('used_count', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
