# Generated by Django 3.1.7 on 2021-06-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('driver_name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('insurance_renewal_date', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
