# Generated by Django 3.2.3 on 2021-06-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(default='photos/user.png', upload_to='', verbose_name='Uploaded image'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
