# Generated by Django 3.2.2 on 2021-05-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('mobile', models.IntegerField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('joindate', models.DateField()),
                ('trips', models.IntegerField()),
                ('status', models.CharField(choices=[('T', 'Trip'), ('A', 'Available'), ('L', 'Leave')], max_length=1)),
            ],
        ),
    ]
