# Generated by Django 3.2.3 on 2021-06-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20210526_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='ageWorker',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='worker',
            name='gender',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='worker',
            name='license',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='worker',
            name='photo',
            field=models.ImageField(default=None, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
