# Generated by Django 3.1.7 on 2021-06-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_alter_worker_rent_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
