export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";


export const CREATE_WORKER = "CREATE_WORKER";
export const RETRIEVE_WORKERS = "RETRIEVE_WORKERS";
export const UPDATE_WORKER = "UPDATE_WORKER";
export const DELETE_WORKER = "DELETE_WORKER";
export const DELETE_ALL_WORKERS = "DELETE_ALL_WORKERS";

export const CREATE_PASSENGER = "CREATE_PASSENGER";
export const RETRIEVE_PASSENGERS = "RETRIEVE_PASSENGERS";
export const UPDATE_PASSENGER = "UPDATE_PASSENGER";
export const DELETE_PASSENGER = "DELETE_PASSENGER";
export const DELETE_ALL_PASSENGERS = "DELETE_ALL_PASSENGERS";

export const CREATE_VEHICLE = "CREATE_VEHICLE";
export const RETRIEVE_VEHICLES = "RETRIEVE_VEHICLES";
export const UPDATE_VEHICLE = "UPDATE_VEHICLE";
export const DELETE_VEHICLE = "DELETE_VEHICLE";
export const DELETE_ALL_VEHICLES = "DELETE_ALL_VEHICLES";
//Coupons
export const CREATE_COUPON = "CREATE_COUPON";
export const RETRIEVE_COUPONS = "RETRIEVE_COUPONS";
export const UPDATE_COUPON = "UPDATE_COUPON";
export const DELETE_COUPON = "DELETE_COUPON";
export const DELETE_ALL_COUPONS = "DELETE_ALL_COUPONS";

//Fares
export const CREATE_FARE = "CREATE_FARE";
export const RETRIEVE_FARES = "RETRIEVE_FARES";
export const UPDATE_FARE = "UPDATE_FARE";
export const DELETE_FARE = "DELETE_FARE";
export const DELETE_ALL_FARES = "DELETE_ALL_FARES";

//Fares
export const CREATE_PAYMENT = "CREATE_PAYMENT";
export const RETRIEVE_PAYMENTS = "RETRIEVE_PAYMENTS";
export const UPDATE_PAYMENT = "UPDATE_PAYMENT";
export const DELETE_PAYMENT = "DELETE_PAYMENT";
export const DELETE_ALL_PAYMENTS = "DELETE_ALL_PAYMENTS";

//Rents
export const CREATE_RENT = "CREATE_RENT";
export const RETRIEVE_RENTS = "RETRIEVE_RENTS";
export const UPDATE_RENT = "UPDATE_RENT";
export const DELETE_RENT = "DELETE_RENT";
export const DELETE_ALL_RENTS = "DELETE_ALL_RENTS";

//Coordantes
export const CREATE_COORDINATE = "CREATE_COORDINATE";
export const RETRIEVE_COORDINATES = "RETRIEVE_COORDINATES";
export const UPDATE_COORDINATE = "UPDATE_COORDINATE";
export const DELETE_COORDINATE = "DELETE_COORDINATE";
export const DELETE_ALL_COORDINATES = "DELETE_ALL_COORDINATES";
